name: self-updater

services:
  updater:
    image: backenddevelopersltd/luxor-updater-${ENV_NAME:-prod}:latest
    restart: unless-stopped
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
